apiVersion: v1
kind: Pod
metadata: 
  name: httpdpod
spec:
  containers:
    - name: httpdctn
      image: httpd
  tolerations:
    - key: "special"
      operator: "Equal"
      value: "only"
      effect: "NoSchedule"
  nodeSelector:
      kubernetes.io/hostname: node1
