apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity: # 용량 지정
    storage: 1Gi # == 1GB
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs1
  nfs: # nfs 서버에 접속하겠다
    path: /shared
    server: 211.183.3.99