apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev1
  namespace: aws9
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["pods", "deployments", "services", "serviceaccounts", "roles", "rolebindings"]
  verbs: ["create", "delete", "get", "patch", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev1
  namespace: aws9
roleRef:    # 어떤 role 을 
  kind: Role
  name: dev1
  apiGroup: rbac.authorization.k8s.io
subjects:   # 누구에게 부여할 것인가?
- kind: ServiceAccount
  name: dev1
  namespace: aws9