apiVersion: v1
kind: Pod
metadata:
  name: myapp3
spec:
  containers:
    - name: myapp3
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name:  indexcm2-cmap-vol  # volume 이름
          mountPath: /usr/share/nginx/html  # pod의 디렉토리
        - name:  indexcm-cmap-vol
          mountPath: /root/indexcm
  volumes:
    - name: indexcm2-cmap-vol
      configMap:
        name: indexcm2
    - name: indexcm-cmap-vol
      configMap:
        name: indexcm