apiVersion: v1
kind: Pod
metadata:
  name: mydb1
  labels:
    name: mydb1
spec:
  containers:
    - name: mydb1
      image: mariadb:10.3
      ports:
      - containerPort: 3306
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsec
              key: dbrootpwd    # test1234가 dbrootpwd에 포함되어 있음

  imagePullSecrets:
    - name:  dockersec

---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  type: LoadBalancer
  ports:
  - name: dbport
    port: 33061    # LB 포트
    protocol: TCP
    targetPort: 3306
  selector:
    name: mydb1