apiVersion: v1
kind: Pod
metadata:
  name: myssh
spec:
  containers:
    - name: mysshpod
      image: nginx
      volumeMounts:
        - name: mykey
          mountPath: /root/.ssh

  volumes:
    - name:  mykey
      secret:
        secretName: pkey