apiVersion: v1
kind: Pod
metadata:
  name: "mypod2"
  labels:
    app: "web"
spec:
  containers:
  - name: myctn2
    image: "nginx"
    ports:
    - containerPort: 80
  nodeSelector: 
    region: seoul