# shop deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: rlatndls113/aws9:blue
        ports:
        - containerPort: 80
---
# shop svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-shop
spec:
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# blog deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: brian24/aws9:green
        ports:
        - containerPort: 80
---
# blog svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-blog
spec:
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP