apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: sample-app # ScaledObject가 대상으로 하는 Deployment 이름
  pollingInterval: 30  # KEDA가 상태를 확인하는 주기 (초)
  cooldownPeriod: 300  # 마지막 스케일 후 안정화를 위한 대기 시간 (초)
  minReplicaCount: 1   # 최소 Pod 수
  maxReplicaCount: 10  # 최대 Pod 수
  triggers:
  - type: cron  # 시간에 따른 scale 조정정
    metadata:
      timezone: "Asia/Seoul"  # 원하는 시간대
      start: "18 * * * *"      # 시작 시점 (Cron 표현식)
      end: "25 * * * *"       # 종료 시점 (Cron 표현식)
      desiredReplicas: "5"    # 스케일링할 Pod 수

  - type: cpu
    metadata:
      type: Utilization
      value: "40"